### ISSUE TITLE
Possibility to trigger an external flash?

### ISSUE THREAD

**Issue by AnykeyNL** [raspberrypi/userland#114]
Hi,
I really would like to have an option to trigger an external flash, especially now when I can control manual shutterspeed. I build a multi raspberry pi 3d scanner (www.pi3dscan.com), using 39 raspberries and cameras. It is working well, but really need more light to get even better results.

As I suck at C programming :-( I am looking for help. Can anyone help me add an option that a GPIO pin can set high the moment the shutter opens, so that this can trigger an external flash system?

Regards,
Richard

**Comment by Ruffio** [comment]
@AnykeyNL @popcornmix is this still an issue?

**Comment by AnykeyNL** [comment]
not for me as I am using fixed lighting now for my solution.

**Comment by popcornmix** [comment]
This should be implemented now.
