### ISSUE TITLE
raspistill hung in mmal_component_create

### ISSUE THREAD

**Issue by brianolson** [raspberrypi/userland#117]
$ /usr/bin/raspistill -o ~/cam.jpg -v

raspistill Camera App v1.2

Width 2592, Height 1944, quality 85, filename /home/pi/cam.jpg
Time delay 5000, Raw no
Thumbnail enabled Yes, width 64, height 48, quality 35
Link to latest frame enabled  no
Full resolution preview No

Preview Yes, Full screen Yes
Preview window 0,0,1024,768
Opacity 255
Sharpness 0, Contrast 0, Brightness 50
Saturation 0, ISO 400, Video Stabilisation No, Exposure compensation 0
Exposure Mode 'auto', AWB Mode 'auto', Image Effect 'none'
Metering Mode 'average', Colour Effect Enabled No with U = 128, V = 128
Rotation 0, hflip No, vflip No
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000

--hangs forever here--

I was hacking on the raspistill source, and probably a crash in my hacked version of that left the driver in some inconsistent state. So the problem seems to be that the driver doesn't recover when the process that had opened it closes and a new client tries.

running in debugger: gdb --args ./raspistill -o ~/cam.jpg -v

(same output, wait a few seconds, interrupt)

(gdb) where
#0  0xb6dfb700 in sem_wait@@GLIBC_2.4 () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0xb6dbdc48 in mmal_vc_sendwait_message () from /opt/vc/lib/libmmal_vc_client.so
#2  0xb6dbfec0 in mmal_vc_component_create () from /opt/vc/lib/libmmal_vc_client.so
#3  0xb6f91d8c in mmal_component_supplier_create () from /opt/vc/lib/libmmal_core.so
#4  0xb6f92b8c in mmal_component_create_core () from /opt/vc/lib/libmmal_core.so
#5  0x0000eeb4 in create_camera_component (state=0xbeffef70) at RaspiStill.c:787
#6  0x00010830 in main (argc=4, argv=0xbefff2b4) at RaspiStill.c:1524

It has hung on the first line of real content in create_camera_component:
   status = mmal_component_create(MMAL_COMPONENT_DEFAULT_CAMERA, &camera);

**Comment by Ruffio** [comment]
@brianolson is this still an issue?

**Comment by brianolson** [comment]
I haven't hit this in a while. If you want to close the issue that's cool.

**Comment by brianolson** [comment]
Aha! I see I have a close issue button myself. Okay then.

**Comment by DragonEmbers** [comment]
Apologies for the delay in responding. I've just had a chance to go back and look at this issue.
My pi is now up to date and has all the latest software, re-tested and this issue still exists.

-------- Original message --------

**Comment by 6by9** [comment]
Please provide your full testcase - without that you won't get anyone investigating. (Almost all of those supporting Pi are now doing so voluntarily following Broadcom pulling out of the apps processor market in summer 2014).

Please confirm you are NOT using MJPEG. That codec is known to have issues if the FIFO gets full, and I'm not going to look into it further as it is significant rework.
