### ISSUE TITLE
Suspended RPI camera.

### ISSUE THREAD

**Issue by pycat** [raspberrypi/userland#120]
Hi everyone!

Sometimes it happens that the RPI camera is suspended despite the killed her raspistill process. The result is that I can't start a new raspistill process.

Example:
1.Start the process:
```
raspistill -w 640 -h 480 -q 10 -o /home/user/scripts/Image/new_img.jpg -tl 100 -t 99999999 -n -th 0:0:0 &
```
2.After a few hours, kill the raspistill process
```
kill -9 <raspistill_pid>
```
#or
```
killall raspistill
```

No process coming from raspistill when I check in ps -aux, but red-led on camera is still lit, and any new process doesn't work, as if waiting in a queue.

This doesn't happen often.

**Comment by Ruffio** [comment]
@pycat is this still an issue?

**Comment by popcornmix** [comment]
Closing due to lack of response. Feel free to reopen if problem still exists.
