### ISSUE TITLE
raspivid stream to ffmpeg gives "Encoder did not nproduce proper pts, making some up"

### ISSUE THREAD

**Issue by li73772** [raspberrypi/userland#126]
I´m trying to stream audio + video from pi to external player. Using 

raspivid -n -ih -pf high -w 720 -h 405 -fps 25 -vf -t 0 -b 1800000 -o - \
| LD_LIBRARY_PATH=/usr/local/lib /home/pi/git/ffmpeg/ffmpeg -y \
    -i - \
    -f alsa -ac 1 -i hw:1,0 \
    -vcodec copy -acodec libfaac \
    -map 0:0 -map 1:0 \
    -f segment \
    -segment_time 4.0 \
    -segment_format mpegts \
    -segment_list "/var/www/stream.m3u8" \
    -segment_list_size 5 \
    -segment_list_flags live \
    -segment_list_type hls \
    -segment_wrap 10 \
    "stream_segments%08d.ts"

Results in an asynchronous stream and an error message:
[adts @ 0x56f6a0] Encoder did not produce proper pts, making some up.

Streaming via CVLC by:
raspivid -t 0 -ih -pf high -w 1080 -h 720 -fps 25 -o - | cvlc stream:///dev/stdin :input-slave=alsa://plughw:1,0 :live-caching=300 --sout '#transcode{acodec=mpga,ab=128,channels=1,samplerate=44100,vcodec=h264,vb=0,scale=0}:rtp{sdp=rtsp://:8554/}' :sout-all :sout-keep :demux=h264

gives
[0x15d75c8] main input error: demux doesn't like DEMUX_GET_TIME

whicha also seem to be a problem of missing time information in der h264 stream.

Regards
Daniel

**Comment by ericpulvino** [comment]
"no, you have to get the timestamps out of band from the driver and write them as PTS into a container.
Gstreamer will do that for you"

I'm trying to do something almost identical. With similar error messages. From what I gather the RAW h264 stream comes without time references but Gstreamer can make a container and apply the PTS info the stream. 

Video Only Stream:
raspivid -h 972 -w 1296 -br 46 --colfx 120:120 -o - -t 0 -vf -hf | cvlc -v stream:///dev/stdin --sout '#rtp{sdp=rtsp://:8554/}' :demux=h264

Tried adding sound (but failed with errors mentioned above)
raspivid -h 972 -w 1296 -br 46 --colfx 120:120 -o - -t 0 -vf -hf | cvlc -v stream:///dev/stdin --input-slave=alsa://plughw:1,0 --sout '#rtp{sdp=rtsp://:8554/}' :demux=h264

Questions:
--Can I then pass that stream /w PTS info onto cVLC for streaming? 
--What does the syntax for gstreamer look like in this case?

New syntax looks like?
raspivid -h 972 -w 1296 -br 46 --colfx 120:120 -o - -t 0 -vf -hf | gstreamer [some set of options to add pts info] | cvlc -v stream:///dev/stdin --input-slave=alsa://plughw:1,0 --sout '#rtp{sdp=rtsp://:8554/}' :demux=h264
