### ISSUE TITLE
Raspistill buffer flush with standard output

### ISSUE THREAD

**Issue by Pol-on** [raspberrypi/userland#133]
When images are saved to file there is no problem but when the images are sent to standard output using "-o -" sometimes part of an image is missing. To reproduce this you can use
raspistill -w 640 -h 480 -n -t 0 -s -o - | less > test.jpg
In smaller images the problem is better visible because bigger part of the image is missing. 
If the problem happens no more images can be save. 
This is probably caused by a buffer. Not all data go to the output and corrupt the next image. 
I think the solution is relatively simple. The buffer needs to be flashed when the output is finished. 
I use the "-o -" option to get the images to my program. It is faster than saving image to disk and reading them.

**Comment by Ruffio** [comment]
@Pol-on does the fix work?

**Comment by Pol-on** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Yes, it does.
It was very simple.
Best wishes
Adam
 
Dnia Pi±tek, 26 Czerwca 2015 23:48 Rasmus Christiansen <notifications@github.com> napisa³(a)

@Pol-on does the fix work?
