### ISSUE TITLE
raspistill -o filename produces segfault as soon as there is a % in the filename

### ISSUE THREAD

**Issue by msperl** [raspberrypi/userland#142]
Hi!

```raspistill -o filename-%s.jpg```
triggers a segfault as long as the pattern is not a valid sprintf pattern with an integer argument.

I was actually trying to run a strftime format like "file-%Y%m%d-%H:%M:%S.jpg" as the filename when I found this.

Maybe you should implement some other replacement scheme, that does not "hickup" with a segfault or at least do some validity checks on the filename patttern given...

Martin

**Comment by Ruffio** [comment]
@JamesH65 whats the status on this one?

**Comment by 6by9** [comment]
For timelapse mode the frame number is inserted in the filename by using sprintf(filename, template, frame_num), where template is the filename passed from the command line. The expectation is that the user will insert %d in the string at the appropriate place. 
Insert %s and it tries to treat the frame number as a string, hence the segfault. 

Yes, the code could do some validity checking to ensure the supplied string either has %d or %%, rejecting any other %<char>. Yes it could expand all invalid occurrences of %<char> with %%<char>, but seeing as it is only demo code that seems a little excessive.

**Comment by msperl** [comment]
Is it really just demo code?

I guess people are using the command-line inside of shell-scripts and such, so it should be stable and not segfault...

**Comment by JamesH65** [comment]
Indeed. I wrote it, put in rudimentary error checking, but it's never been
claimed it's production ready - hence demo code, and hence I put in quite a
few comments in the code to make it easier to understand. I was expecting
by now that people would have taken the code and either written their own
versions or hardened the base code. No such luck. If I have time I might be
able to spend some effort on it, but I would prefer people just make
corrections/additions, send in pull requests, where they will be peer
reviewed and accepted as and when.

**Comment by 6by9** [comment]
I have a patch for this on my laptop that should sanity check the filename. 
Not checked it yet as I didn't have a Pi to hand, and can't cross-compile it under Cygwin (or not that I've been bothered to solve).

My update was just that I was bored so going through issues trying to knock a bundle on the head (there are a load where the reporter hasn't responded to questions, and/or have been fixed but not closed).

**Comment by 6by9** [comment]
Patch pushed to my branch and PR created as https://github.com/raspberrypi/userland/pull/279

**Comment by 6by9** [comment]
PR merged. Please close if happy.
