### ISSUE TITLE
mmal definition for enabling disabling SEI message in h264 encoder

### ISSUE THREAD

**Issue by abhimanyuv1** [raspberrypi/userland#144]
Hello, i wanted to enable SEI message in h264 header, i can see OMX parameter for the same but didnt find similar for mmal.

OMX_IndexParamBrcmVideoAVCSEIEnable
http://home.nouwen.name/RaspberryPi/documentation/ilcomponents/prop.html#OMX_IndexParamBrcmVideoAVCSEIEnable

Do we have any other way to do this?

Thanks

**Comment by Ruffio** [comment]
@6by9 is this ready for testing?

**Comment by 6by9** [comment]
It appears that this was released back on 27 Mar 2014 based on the reference popcornmix has made in raspberrypi/firmware. I would expect that to do the job unless someone tells me otherwise.

**Comment by popcornmix** [comment]
@abhimanyuv1 okay to close?

**Comment by abhimanyuv1** [comment]
Yes.
