### ISSUE TITLE
 raspiyuv: feature request

### ISSUE THREAD

**Issue by vlachoudis** [raspberrypi/userland#145]
Is it possible to include the "-k" and "-s" option already existing in raspistill to raspiyuv.
Using raw data it improves greatly the performance of my program rather than compressing and decompressing a jpg image

**Comment by Ruffio** [comment]
@JamesH65 whats the status og this issue?

**Comment by 6by9** [comment]
Done with commit https://github.com/raspberrypi/userland/commit/1a7a8b99ed292d7f5fbff47a043afb58d79451dd back in July 2014.

**Comment by 6by9** [comment]
@vlachoudis Please close unless you think there is further work to do.

**Comment by vlachoudis** [comment]
Thank you
