### ISSUE TITLE
raspistill timelapse: additional delay between frames 0.5s

### ISSUE THREAD

**Issue by vlachoudis** [raspberrypi/userland#146]
The timelapse feature in raspistill cannot work with settings below 500-600ms. It seems there is delay (some sort of re-initialization) between the frames

"Finished capture XX"
(about 500ms delay here)
"Starting capture XX"

resulting in many frames dropping.

For example the command
raspistill -v -tl 200 -o /run/shm/test%d.jpg -t 10000 -n -w320 -h240

with whatever setting on tl < 700ms it always results in frame dropping
with 100 it drops about 5-6 frames between each capture 
with 200 about 3 frames
with 500 about <1 frame.
With what ever setting I can collect max 18 frames over a period of 10s.

While I see reports on the web that they could go down to 200ms.
http://www.raspberrypi.org/phpBB3/viewtopic.php?t=54361&p=417302
The same delay occurs also with the "-s" triggering

**Comment by Ruffio** [comment]
@JamesH65 any status?

**Comment by waveform80** [comment]
The raspistill demo application uses the camera's still port which requires a mode switch for each frame captured. The mode switch eats up quite a bit of time and I doubt you'd get beyond 2fps using it. To get faster, either capture from the video port or record video and extract frames on the fly (probably easiest with MJPEG - there's an example of this [with picamera](https://gist.github.com/waveform80/263b9c8bdcb1e9b79749)). Just be aware you won't get the same quality as the still port (the captures will look more like video frames).

**Comment by 6by9** [comment]
Or use -bm for burst mode. That tells the GPU that it is doing a sequence of captures, and stops it switching back to preview mode in between.

**Comment by vlachoudis** [comment]
Thank @6by9 I will give it a try.

**Comment by Ruffio** [comment]
@vlachoudis did it solve your issue?

**Comment by vlachoudis** [comment]
Sorry, but I've abandoned this project. I am using the RPi for another task now.

**Comment by Ruffio** [comment]
@vlachoudis then please close the issue... Thanks.

**Comment by vlachoudis** [comment]
Thank you
