### ISSUE TITLE
tvservice - composite video problems after mode switch

### ISSUE THREAD

**Issue by redhawkuk** [raspberrypi/userland#173]
If I run the following:
tvservice -o
tvservice -c "PAL 4:3"
the screen is blanked i.e. black with no flashing cursor, the same is true if I switch from PAL to NTSC and then back to PAL mode.
To fix this I've found that attempting to run startx via remote ssh and then cancelling with Ctrl + C resets the screen back to working order.
Running fbi or startx from local console would probably also work (mode switch) although I've not tried this yet.

Is there a problem with tvservice I don't see any additional options such as blank / unblank screen after mode switch??

While on the subject of composite video I believe that sdtv_mode=3 in /boot/config.txt is handled incorrectly for PAL-M (Brazilian PAL).
According to the Wikipedia website PAL-M is identical to NTSC frame rate and resolution but uses incompatible colour encoding.
When switching into PAL-M mode via tvservice -c "PAL_M 4:3" my video capture card (BT878) is still able to decode composite video as PAL but with incompatible colour encoding.
If the Pi had truly switched in NTSC resolution and frame rate I should not be able to receive a stable picture with PAL decoding.
I can only conclude that PAL-M is not handled correctly by the provided firmware / software.

**Comment by Ruffio** [comment]
@redhawkuk is this still an issue?

**Comment by popcornmix** [comment]
Closing due to lack of response.

**Comment by franmagneto** [comment]
I have this issue, when I use `sdtv_mode=3` or run `tvservice -c "PAL_M 4:3"` I get PAL resolution (720x576), but the expected is the same as NTSC (720x480, 60Hz). It also shows no color.
