### ISSUE TITLE
Build failure with CLang

### ISSUE THREAD

**Issue by kientzle** [raspberrypi/userland#19]
Building with Clang fails because Clang is stricter about implicit type conversions than GCC.  (This is on FreeBSD, which is in the process of switching the system compiler for ARM from GCC to clang.)  The specific error is pasted below.

One possible fix would remove -Werror from mmal/CMakeLists.txt.  Another would add explicit casts to these two assignments.  Clang complains about a number of other similar conversions elsewhere but those don't have -Werror enabled, so those don't break the build.

[ 94%] Building C object interface/mmal/vc/CMakeFiles/mmal_vc_client.dir/mmal_vc_client.c.o
/usr/home/tim/projects/crochet-rpi/vcuserland/interface/mmal/vc/mmal_vc_client.c:102:13: error: 
      implicit conversion from enumeration type 'VCOS_STATUS_T' to different
      enumeration type 'MMAL_STATUS_T' [-Werror,-Wenum-conversion]
   status = vcos_semaphore_create(&waitpool->sem, VCOS_FUNCTION,
          ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/home/tim/projects/crochet-rpi/vcuserland/interface/mmal/vc/mmal_vc_client.c:110:16: error: 
      implicit conversion from enumeration type 'VCOS_STATUS_T' to different
      enumeration type 'MMAL_STATUS_T' [-Werror,-Wenum-conversion]
      status = vcos_semaphore_create(&waitpool->waiters[i].sem,
             ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
*** [interface/mmal/vc/CMakeFiles/mmal_vc_client.dir/mmal_vc_client.c.o] Error code 1

Stop in /usr/home/tim/projects/crochet-rpi/vcuserland/build/arm-freebsd/release.
*** [interface/mmal/vc/CMakeFiles/mmal_vc_client.dir/all] Error code 1

Stop in /usr/home/tim/projects/crochet-rpi/vcuserland/build/arm-freebsd/release.
*** [all] Error code 1

Stop in /usr/home/tim/projects/crochet-rpi/vcuserland/build/arm-freebsd/release.

**Comment by Ruffio** [comment]
@kientzle is this still an issue?

**Comment by kientzle** [comment]
Certainly not.
