### ISSUE TITLE
Apparent typo?  Use = for assignment, not ==

### ISSUE THREAD

**Issue by kientzle** [raspberrypi/userland#20]
Sorting through compiler warnings; this looks like a real bug; the apparent intent of this code is to change the group in this case, but it looks like someone typed "==" where they intended "=".

/usr/home/tim/projects/crochet-rpi/vcuserland/interface/vmcs_host/vc_vchi_tvservice.c:1564:13: warning: equality
      comparison result unused [-Wunused-comparison]
      group == HDMI_RES_GROUP_CEA;
      ~~~~~~^~~~~~~~~~~~~~~~~~~~~
/usr/home/tim/projects/crochet-rpi/vcuserland/interface/vmcs_host/vc_vchi_tvservice.c:1564:13: note: use '=' to turn
      this equality comparison into an assignment
      group == HDMI_RES_GROUP_CEA;
            ^~
            =
1 warning generated.

**Comment by Ruffio** [comment]
@kientzle is this still an issue?

**Comment by kientzle** [comment]
Looks like this has been fixed.
