### ISSUE TITLE
Noise when using the stencil in OpenGL drawing

### ISSUE THREAD

**Issue by magomez** [raspberrypi/userland#207]
hi!

I'm working with the RPi buildroot stored in https://github.com/Metrological/buildroot, doing some development using Qt5 and OpenGL. That buildroot config is currently using version a59842a068cbd19e262701f30014499e9070fbf6 of rpi-userland, despite I've been able to reproduce the issue in former versions.

The problem seems to be that using the stencil to draw paths in OpenGL is causing some noise to be visible in the final result, like the one in this image:
![img_20141010_101153](https://cloud.githubusercontent.com/assets/1577053/4589672/e5890d1a-5056-11e4-93cc-a5756a2b95b9.jpg)

I have been able to reproduce the problem by drawing with Qt, both with text (with size bigger than 65px stencil is used) and SVG paths, and this noise is not reproducible in any other platform I tried (tested on desktop and also another couple of devices with GLES2 implementation), which suggests that the problem is in the RPi GLES2 implementation and not in Qt.

Something I observed is that the noise pattern doesn't seem to be random. In different executions of a test the noise in the same paths seems to be always the same.

I have a simple testcase to reproduce the issue. It's located in the stencil directory of the https://github.com/magomez/qttests repository.

Please feel free to request more information if you need it :)

Regards!

**Comment by Ruffio** [comment]
@magomez is this still an issue?

**Comment by magomez** [comment]
yes, it is still happening in version b834074d0c0d9d7e64c133ab14ed691999cee990

**Comment by JamesH65** [comment]
I vaguely remember a memory overwrite in OGL that was fixed - does this error still occurs (Yes, I know its been a long time!)

**Comment by magomez** [comment]
I can't test this anymore as we have moved away from qt time ago. I'll close this so it's not bothering anymore. Thanks!
