### ISSUE TITLE
MJPEG bitrate and quality settings do not work

### ISSUE THREAD

**Issue by andyg24** [raspberrypi/userland#209]
MJPEG encoding bitrate and quality settings appear to be ignored by the Broadcom driver. Someone reported this a while ago here:

http://www.raspberrypi.org/forums/viewtopic.php?t=75325&p=539055

 This is not something that can be fixed in PiCamera, but perhaps it is worth updating documentation to state that the settings have no effect in the current firmware?

**Comment by Ruffio** [comment]
@andyg24 is this still an issue?

**Comment by popcornmix** [comment]
Closing due to lack of response.
