### ISSUE TITLE
Possible missing header in libraspberrypi-dev package?

### ISSUE THREAD

**Issue by jusme101** [raspberrypi/userland#213]
Building a custom mmal component based on passthrough.c from git://github.com/raspberrypi/userland.git needs mmal_events_private.h, which is not installed in /opt/vc/include/interface/mmal/core/ from the libraspberrypi-dev package, although it's #included from mmal_port_private.h, which is present.
                                                                  
By copying the file from a git clone all is well, but I'd like the code to be buildable just using the installed packages.

**Comment by asb** [comment]
Thanks for the report. The libraspberrypi-dev package is built from the firmware repo, which doesn't contain this header file. Sounds like a bug for @popcornmix

**Comment by popcornmix** [comment]
Yes, will add in next firmware update.

**Comment by jusme101** [comment]
Many thanks!

**Comment by jvcleave** [comment]
Any chance of getting this in a gist?

**Comment by popcornmix** [comment]
This was added a month ago:
https://github.com/raspberrypi/firmware/blob/master/opt/vc/include/interface/mmal/core/mmal_events_private.h
https://github.com/Hexxeh/rpi-firmware/blob/master/vc/sdk/opt/vc/include/interface/mmal/core/mmal_events_private.h
