### ISSUE TITLE
host_applications/linux/apps/raspicam/Makefile is broken

### ISSUE THREAD

**Issue by lurch** [raspberrypi/userland#22]
I ran 'make' and it complained that '../Makefile.include' was missing, so I changed that line in the Makefile to 'include ../hello_pi/Makefile.include'
Then running 'make' complained that 'interface/mmal/mmal.h' was missing, so I added 'INCLUDES+=-I../../../..' to the Makeile.
Then running 'make' ran to completion, but it only produced a single 'raspicam.bin' file, rather than the three separate raspistill, raspivid and raspiyuv files as found in /opt/vc/bin/

**Comment by Ruffio** [comment]
@lurch is this still an issue?

**Comment by lurch** [comment]
@popcornmix sorry, I forgot to close this after reading "Or use the cmake files which build them all."
