### ISSUE TITLE
hello_video freezes

### ISSUE THREAD

**Issue by fredericofs** [raspberrypi/userland#253]
My hello_video plays small h264 movies ok.
But freezes along the way when playing longer files.

**Comment by fredericofs** [comment]
fixed when removing timeout, I am sending a pull request

**Comment by tvjon** [comment]
[hello_audio.bin.zip](https://github.com/raspberrypi/userland/files/2928520/hello_audio.bin.zip)

Attached is a zip of compiled hello_audio.bin

When it runs, there's an anoying buzz present in the audio it produces.

Typical audio files played through the audio jack sound fine.

$ vcgencmd version
Feb 12 2019 22:14:33 
Copyright (c) 2012 Broadcom
version 8eff5e4023657a8b3b59e1f90dc966f62d74908c (clean) (release) (start_db)

$ uname -a
Linux sa1 4.19.20-v7+ #1201 SMP Tue Feb 12 22:10:44 GMT 2019 armv7l GNU/Linux
