### ISSUE TITLE
Using raspistill with -tl and "-a 12" take the same date and time in every picture

### ISSUE THREAD

**Issue by developez** [raspberrypi/userland#265]
I am using the parameters -tl and -a in this way:

    raspistill -w 640 -h 480 -vf -q 10 -o /[folder]/pic.jpg -tl 200 -t 9999999 -th 0:0:0 -a 12

In the pic the same date and time is write, it never changes.

**Comment by JamesH65** [comment]
Probably best to ask this question on the forums, where the commands can be explained more fully.

**Comment by developez** [comment]
Ok, I though that was a bug.
