### ISSUE TITLE
printf for int64_t should require PRId64

### ISSUE THREAD

**Issue by atupone** [raspberrypi/userland#278]
I got https://bugs.gentoo.org/show_bug.cgi?id=570400
My guess is that the code should use PRId64 for format string when printing int64_t

**Comment by 6by9** [comment]
Feel free to create a pull request. 
Seeing as PRId64 is defined as "lld" in inttypes.h, and that is what is used at interface/vmcs_host/linux/vcfilesys.c:246, this is only cosmetic so not going to be a high priority to fix.
