### ISSUE TITLE
requesting an intra frame while recording

### ISSUE THREAD

**Issue by chetanbnaik** [raspberrypi/userland#284]
Hello Developers,

I am using picamera python module to capture video stream. I want to request a key frame (intra frame) while video recording is in progress. What is the correct way of doing this through mmal?

Many thanks for answering this quite a basic question.

**Comment by JamesH65** [comment]
Please ask this sort of question on the Raspberry Pi forums - there is a camera section for exactly this sort of thing.

**Comment by 6by9** [comment]
Plus if you're using picamera then you should really be looking at https://github.com/waveform80/picamera
From MMAL, you're after MMAL_PARAMETER_VIDEO_REQUEST_I_FRAME - https://github.com/raspberrypi/userland/blob/master/interface/mmal/mmal_parameters_video.h#L54
