### ISSUE TITLE
example_basic_2.c run error with MMAL_EIO

### ISSUE THREAD

**Issue by myw31415926** [raspberrypi/userland#285]
Hello:
Today, I run mmal/test/examples/example_basic_2.c, but it doesn't work. as follows: 

> pi@raspberrypi ~/mmal_test $ ./mmal_example_basic_2 video3.h264 
> stats: 0, 0status: 0
> status: 0
> vc.ril.video_decode:out:0(RGB2)
>  type: 3, fourcc: RGB2
>  bitrate: 0, framed: 0
>  extra data: 0, (nil)
>  width: 1280, height: 720, (0,0,1280,720)
> start decoding
> sending 1920 bytes
> stop decoding

But I found **context.status** is **MMAL_EIO**, it means **I/O error**, why? How to solve the problem? 
Thanks!

**Comment by 6by9** [comment]
The main error is due to MMAL_PARAMETER_ZERO_COPY being enabled incorrectly. 
Disable that (set to MMAL_FALSE) and it runs further, but still stalls for me. Seeing as it doesn't appear to do any checks for output format changes, I'm not sure what I expect to work or not.
