### ISSUE TITLE
What is MMAL_COMPONENT_DEFAULT_MIRACAST?

### ISSUE THREAD

**Issue by Terminus-IMRC** [raspberrypi/userland#288]
c.f. https://github.com/raspberrypi/userland/blob/master/interface/mmal/util/mmal_default_components.h#L68

What is ```MMAL_COMPONENT_DEFAULT_MIRACAST``` and how do I use it?
Or is it just an internal function?

**Comment by 6by9** [comment]
Not built on Pi.
For other projects there was a single component that would create a miracast encoded video stream, with various optimisations. I'm not certain all the relevant hooks are even present on Pi.
Ignore it.

**Comment by Terminus-IMRC** [comment]
Thank you for your reply.
I hope I can use it also on Pi...!

**Comment by Terminus-IMRC** [comment]
FYI: "miracast" strings were first seen in https://github.com/raspberrypi/firmware/commit/d3ada6f943818eecda9a81c1091631d3971798b2 .
