### ISSUE TITLE
Can't run java2d with opengl

### ISSUE THREAD

**Issue by fheday** [raspberrypi/userland#289]
When using this driver and  trying to run a java program (in my specific case, BlueJ), using the opengl pipeline:

`java -Dsun.java2d.opengl=true  -Dawt.useSystemAAFontSettings=on -cp "/usr/share/bluej/bluej.jar:/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/lib/tools.jar" bluej.Boot`

 I get the following message:

> unknown NIR ALU inst: vec1 ssa_371 = fddx ssa_316
> Aborted

**Comment by popcornmix** [comment]
Pi doesn't support OpenGL, only OpenGLES, so this is unlikely to work.
It is possible the very experimental new GL driver might make this more likely to work, but currently it is very experimental.
