### ISSUE TITLE
[RPi Camera] Bottom line of image looks strange

### ISSUE THREAD

**Issue by shrx** [raspberrypi/userland#30]
I did a night time lapse test and when I analysed the images I found something curious:
Applying a "multiply" effect revealed a strange line at the bottom of the images that looks like a part of the image is corrupted. This is more noticeable with darker images, and some of them were pitch black - that's why I managed to spot it.
The code I used to capture the images: `    raspistill -o image$i.jpg -ex auto -q 50 -w 1440 -h 1080 -ev 10 --vflip`
This issue can be reproduced with these settings every time, but it's less noticeable on brighter images (they become too bright with big multiply values to see anything).
Some examples:
A pitch black image: http://shrani.si/?2E/bR/kCV2tgK/image10.jpg
Same image, cropped and multiplied by factor 100 to show the issue:
![example 1](http://shrani.si/f/3D/WA/42TxdrX/ex1.png)

A brighter image: http://shrani.si/?3b/2O/69INt2k/test.jpg
Same image, cropped and multiplied by factor 100 to show the issue:
![example 2](http://shrani.si/f/A/HU/3MUJg6ve/ex2.png)

It appears this issue does not occur when no additional settings are used: `raspistill -o test.jpg`

@JamesH65 suggested:
> I think that is because your vertical height is not a multiple of 16.

I agree that this seems a reasonable explanation.

**Comment by Ruffio** [comment]
@shrx is this still an issue?

**Comment by shrx** [comment]
@Ruffio I will check tonight when it's dark, my RPi camera is in a fixed location now recording the sky.

**Comment by shrx** [comment]
It appears this is fixed, I haven't noticed the color bands since.
