### ISSUE TITLE
How to get YUV data from decoder after decoding in hellovideo application?

### ISSUE THREAD

**Issue by mukeshkumard** [raspberrypi/userland#327]
Hi,
I am running userland (hellovideo) application in Android rpi3. After fetching h264 data from file OMX_EmptyThisBuffer() is invoked to transfer the buffer to decoder. In my case after decoding the data,I am not able to see the video on screen. So to test whether the h264 data is decoded to YUV data, can I use OMX_FillThisBuffer()  in video.c to get the decoded buffer from decoder. Will the decoder give me the YUV data(back to application) through that call?

**Comment by JamesH65** [comment]
This is a technical question rather than a bug report and should therefor
for be posted on the Raspberry Pi forums, not here.

**Comment by mukeshkumard** [comment]
Okay ThankYou!!!
