### ISSUE TITLE
raspicam --ev -10..10 is not EV

### ISSUE THREAD

**Issue by towolf** [raspberrypi/userland#34]
I don’t know what this is doing but what it is setting is not EV, i.e., log_2 scale. It’s quite small increments. Please clarify

**Comment by Ruffio** [comment]
@towolf is this still an issue?

**Comment by 6by9** [comment]
PR #279 now merged which adds help text stating that EV is in steps of 1/6 stop.
Please close unless you think there is something further to do.

**Comment by Ruffio** [comment]
@towolf is this still an issue? It looks like it has been solved.

**Comment by towolf** [comment]
No
