### ISSUE TITLE
Illegal backslash escape code on line 1788 of RaspiStill.c

### ISSUE THREAD

**Issue by pelwell** [raspberrypi/userland#369]
GitHub's viewer highlights the escape sequence `\%s` as being suspicious/wrong. See: https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/raspicam/RaspiStill.c#L1788

Comparing it to line 1802 (https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/raspicam/RaspiStill.c#L1802) suggests it should be `\n%s`, or you may want to remove the backslash - it depends whether a blank line is required.

**Comment by JamesH65** [comment]
Agreed. Typo.

**Comment by JamesH65** [comment]
Fixed with commit deeb9593a159701a76261b02773439eef24b2cfa
