### ISSUE TITLE
feature suggestion for raspivid: timestamp in file name option when recording in segments

### ISSUE THREAD

**Issue by jdesbonnet** [raspberrypi/userland#385]
I am using raspivid to record in segments, but I need to preserve the exact time the recording started (file lastmodified stamps are easily changed by accident). A nice option would be to use a timestamp in the filename instead of a sequential counter.

**Comment by jdesbonnet** [comment]
I've got a very small modification that achieves this:
https://github.com/jdesbonnet/userland/tree/segmented_recording_filename_timestamps

**Comment by JamesH65** [comment]
Interesting idea that has no impact elsewhere. Thoughts @6x9 ?

Would need a small code tidy and the docs updating...!!

On 11 April 2017 at 12:14, Joe Desbonnet <notifications@github.com> wrote:

> I've got a very small modification that achieves this:
> https://github.com/jdesbonnet/userland/tree/segmented_
> recording_filename_timestamps
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jdesbonnet_userland_tree_segmented-5Frecording-5Ffilename-5Ftimestamps&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=3fVe4Z_ELFcTKQFFTWux6VUw4eXtiNQPQETTIDaJIP8&s=jJ3MUL1vIdH940mCfka5hk1yPDOcPOI1FwBu-qHs9Dg&e=>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_raspberrypi_userland_issues_385-23issuecomment-2D293225936&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=3fVe4Z_ELFcTKQFFTWux6VUw4eXtiNQPQETTIDaJIP8&s=ZAcGvgIQtl3Pp7j94RXiYQf5Aa1_tz17TN3ohrM6Dj0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADqrHZOWbtNY6YQWFle7kDlFjVj0RBK0ks5ru2B7gaJpZM4MnbZu&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=3fVe4Z_ELFcTKQFFTWux6VUw4eXtiNQPQETTIDaJIP8&s=pkzqQVqgHhB869YkW83a2MBqd4KaymgJO5lpuy_W3SU&e=>
> .
>



-- 
James Hughes
Principal Software Engineer,
Raspberry Pi (Trading) Ltd

**Comment by 6by9** [comment]
Yes, other than a couple of formatting issues that I've just commented on it looks fine. Please create a pull request for it (I haven't checked that your branch is based off the top of tree, but the change cherry-picked fine)

I can't quite believe that you can't printf a time_t without a cast, but it appears that way. The cast on tv_nsec can be avoided with %03ld, but in this case it makes little difference due to the divide.

**Comment by jdesbonnet** [comment]
Thanks for the feedback. Sorry, that was just interned as an initial hack to see if was an easy thing to do. Ideally the user should be able to pass the date formatting string in standard C library format, but the simple test for "%d" vs "%s" won't work in that case. Perhaps that over complicates it a bit.

**Comment by JamesH65** [comment]
@jdesbonnet Are you planning a PR to implement this?

**Comment by JamesH65** [comment]
@jdesbonnet We would need a PR to make this change.

This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.

**Comment by JamesH65** [comment]
Fixed by #479
