### ISSUE TITLE
CPU detection.

### ISSUE THREAD

**Issue by ED6E0F17** [raspberrypi/userland#393]
hello_fft relies on "/proc/device-tree/axi"
(from https://github.com/raspberrypi/userland/blob/master/host_applications/linux/libs/bcm_host/bcm_host.c#L164)
which no longer exists.

**Comment by pelwell** [comment]
Yes, annoyingly that is the one piece of information that was used in the "axi" subtree, and it is dynamic in the sense that its value depends on the `disable_l2cache` config setting. It's probably necessary to restore this one property.

**Comment by popcornmix** [comment]
Can you test latest rpi-udpate firmware?

**Comment by ED6E0F17** [comment]
Working as expected. After updating just the firmware: /proc/device-tree/axi is present, and my Pi2 has a working hello_fft with "#define GPU_FFT_USE_VC4_L2_CACHE 1" enabled (set for Pi1 use).
