### ISSUE TITLE
Create official Releases

### ISSUE THREAD

**Issue by makefu** [raspberrypi/userland#428]
Tracking the master is cumbersome for the linux distributions and packagers. It would be great if you create separate releases with a version number.

Thanks!

Reference: http://keepachangelog.com/

**Comment by JamesH65** [comment]
@XECDesign Any thoughts?

**Comment by XECDesign** [comment]
For Raspbian, we pull in the pre-compiled binaries from https://github.com/raspberrypi/firmware/tree/stable. It's up to @popcornmix and @pelwell whether they want to group changes into releases and keep a changelog. I'm not sure that there's enough of a benefit to justify it.

**Comment by JamesH65** [comment]
Closing, this is more of a Pi linux issue that userland. Please create a new issue there if this is still applicable.
