### ISSUE TITLE
 how to send the picture a linux pc without writing rpi sd card, when i take a picture with raspicam

### ISSUE THREAD

**Issue by busrakb** [raspberrypi/userland#449]
Hi,

I want to change  photo path. But i dont want to save in rpi sd card. I want to send that photo to my linux pc. I can do when i take a photo with raspicam, firstly save the rpi sdcard and then  send my linux pc via ssh. But i dont want to do it. I want to write directly to my linux pc. How can i do it? Can you help me?

**Comment by pelwell** [comment]
Issues are intended to be problems or bug reports. Questions like this are best asked in the forums. But the documentation says that specifying `-` as the output file name (`raspicam ... -o - ...`) will send the photos to stdout, so try:
```
$ ssh pi@<addr> raspicam ... -o - ... > pic.jpg
```
