### ISSUE TITLE
MMAL is not getting/setting the dynamic frame rate properly

### ISSUE THREAD

**Issue by DMV27** [raspberrypi/userland#456]
The high end of the dynamic frame rate is not being get/set properly. For example, when I set the max frame rate to 10 I am receiving 30 fps when the shutter speed is low enough. The code below is using xFramerateLow instead of xFramerateHigh for the mmal->fps_high.

https://github.com/raspberrypi/userland/blob/a1b89e91f393c7134b4cdc36431f863bb3333163/interface/mmal/openmaxil/mmalomx_util_params_camera.c#L395-L404

**Comment by 6by9** [comment]
The firmware doesn't use the interface/mmal/openmaxil mappings, so whilst I'll agree that this is a bug I don't believe it has any effect for any app using MMAL.
If you want to use IL, then the logical choice is to use IL directly.
Have you got a real example where you are seeing incorrect behaviour? (PRs are welcome if you wish to fix it)

This code was intended for a platform where we (Broadcom) were moving away from IL, but still had to support it to clients. That platform never fully happened, so it's pretty orphaned code.
TBH we (Raspberry Pi) should probably delete it as dead, but there is a slim chance that others have used it for some odd reason. I guess the simplest approach is to add a README.md to that directory stating the situation.
