### ISSUE TITLE
raspivid segmentation fault with latest Stretch

### ISSUE THREAD

**Issue by Hermann-SW** [raspberrypi/userland#464]
pi@raspberrypi3Bplus:~ $ raspivid -md 7 -fps 64 -o test.h264
Too many macroblocks/s: Increasing H264 Level to 4.2
pi@raspberrypi3Bplus:~ $ raspivid -md 7 -fps 65 -o test.h264
mmal: Too many macroblocks/s requested
Segmentation fault
pi@raspberrypi3Bplus:~ $

**Comment by ethanol100** [comment]
You are requesting 1920x1080 at 65 fps which is not valid within H264 Level 4.2.
Raspivid could check for out of bound values, but then we would need to lower the fps or the resolution and how should rasapivid decide?

**Comment by 6by9** [comment]
Very true that it is well outside the capabilities of the hardware, but it also shouldn't segfault.

It should be a 2 minute job with gdb to see where it is throwing the seg fault, but I can't see it immediately, and I haven't got a suitable system to hand.

**Comment by Hermann-SW** [comment]
>  but it also shouldn't segfault.
>
That was why I reported.
