### ISSUE TITLE
Option to disable lens shading correction if possible

### ISSUE THREAD

**Issue by towolf** [raspberrypi/userland#50]
It’s quite easy to unscrew the little lens and do focal imaging with other optics.

Based on the stadard lens, the post-processing assumes a fall-off towards the edge and compensates with a filter. Once the optics change this filter interferes with making good images.

Would be neat if this could be turned off, on-the-fly if possible.

**Comment by Ruffio** [comment]
@towolf  is this still an issue?

**Comment by Ruffio** [comment]
@JamesH65 how is this coming along?

**Comment by JamesH65** [comment]
I do not have access to the GPU source, and haven't had for some years. @6by9 is the only option on this one.

**Comment by Ruffio** [comment]
@JamesH65, then I suggest that you no longer are assigned to this issue...
@6by9 ???

**Comment by 6by9** [comment]
Not a priority for me.
I'm playing with that code for other reasons and there appear to be interactions elsewhere.

**Comment by Ruffio** [comment]
@6by9, who can remove @JamesH65 as assignee on these issues?

**Comment by 6by9** [comment]
Implemented - see https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=190586
