### ISSUE TITLE
image decode example using mmal

### ISSUE THREAD

**Issue by ksharindam** [raspberrypi/userland#500]
I am struggling to decode jpeg image using mmal.
There is a image render example but no image decode example.
It will be helpful if there is a image decode example in userland.

**Comment by glddiv** [comment]
Is this you want?
https://github.com/raspberrypi/userland/tree/master/host_applications/linux/apps/hello_pi/hello_jpeg

**Comment by ksharindam** [comment]
No, I want to use mmal for decoding jpeg image. But this example is Openmax based

**Comment by 6by9** [comment]
I'd started on creating a set of MMAL equivalents, but not cleaned it up.
https://github.com/6by9/userland/blob/hello_mmal/host_applications/linux/apps/hello_pi/hello_mmal_jpeg/jpeg.c

One comment made by a colleague is that you don't actually have to have allocated the output buffer pool before you get the MMAL_EVENT_FORMAT_CHANGED event buffer. Events are allocated of an independent pool created by the framework, so you can save a chunk of memory allocation.

**Comment by ksharindam** [comment]
Thank you so much.
I have run the binary file, and it worked.
