### ISSUE TITLE
hello_pi runtime errors

### ISSUE THREAD

**Issue by jwinarske** [raspberrypi/userland#526]
In master, I see runtime errors with hello_pi projects "hello_font", "hello_tiger", and "hello_jpeg".

./hello_font: symbol lookup error: /opt/vc/lib/libbrcmEGL.so: undefined symbol: glPointSizePointerOES

./hello_tiger: symbol lookup error: /opt/vc/lib/libbrcmEGL.so: undefined symbol: glPointSizePointerOES

./hello_jpeg ./3844893.jpeg 
Did not receive executing stat -1
No EOS event on image decoder -1
No EOS event on image resizer -1

**Comment by popcornmix** [comment]
On either raspian or raspian lite run ``rebuild.sh`` in ``/opt/vc/src/hello_pi``
https://www.raspberrypi.org/documentation/usage/demos/

**Comment by jwinarske** [comment]
Using a Raspbian Stretch image (not-Lite), with the legacy driver enabled, it works.

If I have either non-legacy display driver enabled I get "* failed to add service - already in use?".

**Comment by popcornmix** [comment]
Yes, these apps only work with the legacy/firmware 3d driver.
