### ISSUE TITLE
dtmerge is dependant on libdtovl which is not a part of the repository

### ISSUE THREAD

**Issue by slobobaby** [raspberrypi/userland#540]
libdtovl does not seem to exist even though dtmerge depends on it.

I found the code here:

https://github.com/elephos

but it would be better if it was part of this repository.

**Comment by pelwell** [comment]
The source is in this repo: https://github.com/raspberrypi/userland/tree/master/helpers/dtoverlay
The library won't exist until you build it.

**Comment by slobobaby** [comment]
Cool. Thanks for your trouble and the quick response.
