### ISSUE TITLE
userland repo is missing edid_parser and vcdbg

### ISSUE THREAD

**Issue by lurch** [raspberrypi/userland#56]
As discussed here https://github.com/raspberrypi/firmware/commit/470b34d635343bb7c878f12ea696f16ef6318801 the source-code for edidparser and vcdbg is currently unavailable. AFAICT this makes them the only part of the ARM-side code that isn't yet open-sourced.

Creating this issue as a reminder that they ought to be added at some point...

**Comment by wbx-github** [comment]
Hi,

is there any progress made in publishing vcdbg?
I wanna use it on a uClibc based system.

best regards
 Waldemar

**Comment by lurch** [comment]
Just going through some old bugs, and I see that the sources for mmal_vc_diag and libdebug_sym mentioned by @timgover above *are* now in the [userland repo](https://github.com/raspberrypi/userland/commit/30cefd5b8925d6d4a1fb922cd1f0abc85731d7ab). Which just leaves the original `edidparser` and `vcdbg` as the non-source binaries.

@wbx-github perhaps you could use http://unix.stackexchange.com/questions/46478/join-the-executable-and-all-its-libraries or http://stackoverflow.com/questions/16958716/convert-a-dynamically-linked-elf-binary-to-statically-linked as a workaround? (haven't tried either option myself, just found them from googling)

**Comment by kenrestivo** [comment]
I too would like to have the source code to vcdbg. Thanks.

**Comment by Ruffio** [comment]
@lurch is this still an issue?

**Comment by XECDesign** [comment]
yes

**Comment by Ruffio** [comment]
@lurch any comments on this one?

**Comment by TheSin-** [comment]
I just noticed that my repo does not have vcdbg/edid_parser, I'd like to be able to compile and armel/armhf and arm64 version of these for my dist, is there any chance these may become open someday, for those of us that don't want to use raspbian?

**Comment by JamesH65** [comment]
@XECDesign @lurch Any chance we can close this?

**Comment by lurch** [comment]
@JamesH65 If you want to add `edid_parser` and `vcdbg` to https://github.com/raspberrypi/userland/tree/master/host_applications/linux/apps then sure :wink:

**Comment by JamesH65** [comment]
I've no idea where the source is! @popcornmix might have a better idea. Not sure if the licence is OS though.

**Comment by 6by9** [comment]
edid_parser is copyright Broadcom and pulls in various other libraries.
Based on a quick look I'm not sure what edidparser gives you over edid-decode (available from the standard Raspbian repos).

vcdbg likewise has a large number of dependencies, and is copyright Broadcom.

**Comment by lurch** [comment]
...in which case, either this ticket should remain open indefinitely; or `README.md` should be updated to say that this repo will never include the source for the `edid_parser` and `vcdbg` binaries that the `firmware` repo includes. IMVHO of course.

**Comment by pelwell** [comment]
> or README.md should be updated to say that this repo will never include the source for the edid_parser and vcdbg binaries that the firmware repo includes.

I think "...does not contain the source for the edid_parser and vcdbg binaries due to licensing restrictions." would be preferable.

**Comment by JamesH65** [comment]
Which README.md needs updating? I'll fix it when I know!

**Comment by pelwell** [comment]
This one: https://github.com/raspberrypi/userland/blob/master/README.md

**Comment by JamesH65** [comment]
OK, updated the README, so closing.

**Comment by lurch** [comment]
Thanks @JamesH65 :+1:

**Comment by Merlinstail** [comment]
Might be an idea to add where those can be obtained from in either source
or binary form

**Comment by pelwell** [comment]
> Might be an idea to add where those can be obtained from in either source
or binary form

To what does "those" refer? `vcdbg` and `edid_parser`, as explained, are proprietary Broadcom code and will not be released in source form. `edid-decode` is available in Raspbian - it's a standard Debian package, so `sudo apt-get install edid-decode`. You can download (and build) the source in the usual way - see: https://wiki.debian.org/apt-src

**Comment by jakemagee** [comment]
I think @Merlinstail was asking where the binary form of vcdbg and edid_parser can be obtained.  It appears to be here ... https://github.com/raspberrypi/firmware/tree/master/opt/vc/bin , and of course both are located in /usr/bin/ on the Raspbian images.  Also, it appears that "edid_parser" is actually "edidparser" now? Although when ran with no arguments, the help info still references "edid_parser".

**Comment by jakemagee** [comment]
Opened https://github.com/raspberrypi/firmware/issues/927 to see if the edidparser / edid_parser naming needs fixing.

**Comment by lurch** [comment]
> It appears to be here ... https://github.com/raspberrypi/firmware/tree/master/opt/vc/bin

Yeah, that's the softfp version, and the hardfp version (as used in Raspbian) is at https://github.com/raspberrypi/firmware/tree/master/hardfp/opt/vc/bin
(IIRC once upon a time there were separate softfp and hardfp versions of Debian for the Raspberry Pi)

> Also, it appears that "edid_parser" is actually "edidparser" now?

Hmm, looking at both https://github.com/raspberrypi/firmware/commits/master/hardfp/opt/vc/bin/edidparser and https://github.com/raspberrypi/firmware/commits/master/opt/vc/bin/edidparser it seems like the binary has _always_ been named `edidparser`, so I must have made a typo when originally creating this issue :-/

**Comment by mc-requtech** [comment]
If source is not feasible, maybe at least statically built binaries?  The way things are now it's not possible to run `vcdbg` on a musl or uClibc system, which is rather unfortunate.

**Comment by lurch** [comment]
See https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/67#issuecomment-653209729 ?

**Comment by mc-requtech** [comment]
@lurch Thank you.  Looks very unofficial but it does work.  :tada:
