### ISSUE TITLE
Cannot install python3-pip (broken debs)

### ISSUE THREAD

**Issue by hexxter** [raspberrypi/userland#570]
I use "Linux 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux" on a Raspberry pi 3. And i cannot install python3-pip. I think python3-dev is not avalible.

BR Hexxter

**Comment by 6by9** [comment]
Not part of userland.

@XECDesign do you want to triage and shift elsewhere?

**Comment by XECDesign** [comment]
Everything looks okay on our end. This is probably better addressed on the forum.

https://www.raspberrypi.org/forums/viewtopic.php?p=1523664#p1523539

**Comment by 6by9** [comment]
Closing issue as it is covered on the forum.
