### ISSUE TITLE
replace arch in buildme with "uname -m"

### ISSUE THREAD

**Issue by solskogen** [raspberrypi/userland#590]
**Describe the bug**
Not every distribution comes with "arch", which is used in buildme. Replace it with something more portable, like "uname -m"

**To reproduce**
List the steps required to reproduce the issue.

**Expected behaviour**
Successfull build on Arch Linux and Manjaro

**Actual behaviour**
Since arch isn't installed, the build fails.

**Comment by pelwell** [comment]
Submit a Pull Request - for a simple change like that you can do it all in the GitHub GUI.

**Comment by solskogen** [comment]
Done!
