### ISSUE TITLE
cmake vmcs_host error

### ISSUE THREAD

**Issue by nandemonogatari** [raspberrypi/userland#603]
Not sure if it's correct but i had this:

`CMake Error at interface/vmcs_host/CMakeLists.txt:35 (install):
install TARGETS given target "vchostif vcilcs" which does not exist in this directory.`

And i think it's fixed by changing line 29 of /userland-master/interface/vmcs_host/CMakeLists.txt from:
`set(INSTALL_TARGETS "${INSTALL_TARGETS} vcilcs")`
to:
`set(INSTALL_TARGETS ${INSTALL_TARGETS} vcilcs)`

or at least with that change it builds.

(on raspberry pi 3 B+ with Raspbian 9.9)

**Comment by pelwell** [comment]
@daggs1 Do you agree with this change?

**Comment by daggs1** [comment]
seems ok, I'd remove the " from the first SET too

**Comment by popcornmix** [comment]
Yes - just been testing that - I'll push it.

**Comment by gilbertVirgo** [comment]
Still not pushed?
