### ISSUE TITLE
raspistill: feature request: cross-hair for the viewfinder

### ISSUE THREAD

**Issue by afkrause** [raspberrypi/userland#671]
Simple feature request: would it be possible to add a simple cross-hair to the view-finder for raspistill?

that would help to center an object exactly into the middle of the raspicam.

**Comment by 6by9** [comment]
Not easily, no. It would need to be added as an additional display layer over the top of the preview, and whilst that's possible, you then have to mess around with where the --win option has put the preview window, how aspect ratio changes could move the image, etc. 

Far easier to get a small sticker and put it on your display, or a piece of sellotape that you mark your centre point with.

**Comment by afkrause** [comment]
thank you very much. sometimes the easy and obvious solution is hard to see! i will stark raspistill in fullscreen mode and place a sticker right to the centre of my monitor. that should to the trick!

**Comment by 6by9** [comment]
Issue resolved so closing. Please reopen if you feel there is anything further required.
