### ISSUE TITLE
v3d fec00000.v3d : MMU error from client L2T (0) at 0x3xxxxxx, pte invalid

### ISSUE THREAD

**Issue by Ash-S** [raspberrypi/userland#698]

**Comment by 6by9** [comment]
Looks to be an unintended duplicate of #699

**Comment by Ash-S** [comment]
@6by9 ; sorry, it's by mistake. how can I remove this thread?

**Comment by 6by9** [comment]
> sorry, it's by mistake. how can I remove this thread?

You can't, but I have closed it to denote that no further action will be taken on it.
