### ISSUE TITLE
raspiyuv produces excess data when width is not a multiple of 32 or height not a multiple of 16

### ISSUE THREAD

**Issue by jeevesmkii** [raspberrypi/userland#702]
When raspiyuv is invoked with an image width not 32 byte aligned or an image height not 16 byte aligned, the image buffers are aligned to those boundaries. The YUV data then output has some number of bytes of garbage appended to every row, or a number of rows of additional garbage at the end.

To reproduce:
Take a still image with (for example) the raspberry pi camera 2 at its native resolution of 3280x2464 with this command:
raspiyuv -w 3280 -h 2464 -y -o example.y # dump the luma channel only

examine example.y's file size:
ls -la example.y # actual result: 8121344 bytes, expecting 3280x2464 = 8081920 bytes

the file is actually 3296x2464 worth of luma data.
convert to grayscale jpg with this command:
convert -depth 8 -size 3296x2464 gray:example.y example.jpg

gives a JPEG image with 16 columns of garbage on the right hand side.

Expected:
raspiyuv should output exactly width*height luma data or width*height*1.5 yuv data or width*height*3 rgb data.

Actual results:
raspiyuv emits ALIGN(width, 32) and ALIGN(height, 16) data, and any padding is filled with random garbage.

**Comment by 6by9** [comment]
Working as documented.

https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/raspicam/raspiyuv.1#L145 (should be rendered to a man page, but I've not got a live system to confirm)
```
Note that the image buffers saved in
raspiyuv
are padded to a horizontal size divisible by 32, so there may be unused bytes
at the end of each line. Buffers are also padded vertically to be divisible by
16, and in the YUV mode, each plane of Y,U,V is padded in this way.
```

Imagmajik's convert appears to have a crop parameter, so using ```convert -depth 8 -size 3296x2464 -crop 3280x2464 gray:example.y example.jpg``` should crop the active area from the saved buffer in your example.
