### ISSUE TITLE
The `usb-modeswitch-data` package needs to be updated to  ( `usb-modeswitch-data` package (2019-11-28 ))

### ISSUE THREAD

**Issue by morrownr** [raspberrypi/userland#712]
**Describe the bug**

As of the 2021-10-30 release of RasPiOS, the version of the data package used with `usb_modeswitch` is obsolete.

The data file can be found at the upstream location for this utility:

https://www.draisberghof.de/usb_modeswitch/#download

**To reproduce**

Place a `COMFAST CF-WU782AC` USB WiFi adapter in a USB port on a RasPi4B. 

This adapter is a multi-state adapter and needs `usb_modeswitch` to switch it to WiFi mode for things to operate as expected. This same problem applies to several USB WiFi adapters that are currently on the market. The problem is not with the usb_modeswitch executable, it is with the data file that goes with it (the data file should have been updated at the same time as the executable... this may need to be reported to Debian)

**Actual behaviour**

The adapter has a mt7612u chipset and RasPiOS has the mt7612u driver in-kernel but all we get is a storage device icon on screen called "wireless." No WiFi interface is created because the adapter is stuck in storage mode.

**System**
 
* Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW

This applies to all RasPis that have USB ports.

* Which OS and version (`cat /etc/rpi-issue`)?

RasPiOS. Tested today on the 2021-10-30 release.

**Additional context**

The upstream for this utility is:

https://www.draisberghof.de/usb_modeswitch/

A lot of USB WiFi adapters that use mt7612u chipsets are on the market these days and they work really well with RasPi's, well, except for this problem. Request this issue be address as soon as possible.

Thank you.

**Comment by popcornmix** [comment]
This repo is for the userland libraries used for communicating with the GPU.
This issue sounds more like a RPiOS packaging issue so should be reported here:
https://github.com/RPi-Distro/repo/issues/
