### ISSUE TITLE
Changes regarding OMX_Broadcom in arm64 vs legacy rapsbian image

### ISSUE THREAD

**Issue by rubu** [raspberrypi/userland#728]
Maybe this is not the best place to ask this, but I could not find any info, so any pointers would be appreciated (and the issue can be closed then).

What has happened with `OMX_Broadcom.h` and other `vcos` headers in the new (non legacy) Raspbian image? The headers are there in the legacy image, but my software which was using them, does not compile on the new image. Has the functionality been totally removed/deprecated? What is the proper way to use the OMX H.264 decoder and rendering APIs if those headers are gone?

**Comment by popcornmix** [comment]
openmax has been deprecated for a long time, and is not longer installed on RPiOS bullseye.
It is recommended you move to v4l2 for video encode/decode.

You are free to remain on the legacy bullseye image if these interfaces are important to you.

openmax can currently be used on bullseye if you install the libs yourself.
Cloning and building this repo should get you the libs and header files you need.
But be aware these libraries will get no support and may stop working completely in the future.
