### ISSUE TITLE
Alternative of userland in Bullseye

### ISSUE THREAD

**Issue by ChayMahajj** [raspberrypi/userland#739]
Hello everyone, 

I was using userland  library to copy a snapshot of the display in the framebuffer.
After switching to bullseye, my application is no more applicable.
I am looking for an alternative to the userland APIs in order to recreate the same application. 

I appreciate your help.

Best regards,
Chayma.

**Comment by popcornmix** [comment]
Probably best to ask on the [forums](https://forums.raspberrypi.com/).

In general the DRM/KMS world is more security conscious.
There is a single DRM master that has the ability to do operations like this.
You generally can't grab the screen output of another DRM master.

If you are running under a desktop environment, then this is possible using APIs it provides.

If there is no desktop, and another app is DRM master, then it will have to perform the snapshot.
