### ISSUE TITLE
Manual exposure control for raspistill

### ISSUE THREAD

**Issue by dmopalmer** [raspberrypi/userland#76]
This is a request to make the exposure time (shutter speed) an exposed parameter in the API (or if it is already, to document how to use it.)

I would like to set the shutter speed for raspistill.  I want to do technical imaging where I can control what the camera does (and, secondarily, make it do it with as little lag as possible).

If I set --exposure=off then it always takes a 1/100 s image (according to the EXIF).

I have looked through the mmal_parameters_camera.h and don't see any way to set the exposure time, unless it is disguised as e.g. MMAL_PARAMETER_FRAME_RATE, MMAL_PARAMETER_FPS_RANGE, etc.

Since the Raspberry Pi is not an open-source project, I can't go in and see how it is setting the shutter speed.

This capability would be useful for, e.g.:
1) HDR imaging
2) Astronomical imaging
3) structured light scanning
4) photogrametry
and any other purpose where the data is more important than the aesthetics.

**Comment by Ruffio** [comment]
@dmopalmer @jollyjollyjolly is this still an issue?

**Comment by dmopalmer** [comment]
I have not looked at the source code recently, but as of raspistill v.1.38 
$ raspistill -o /tmp/foo.png --exposure verylong
gives a 1/15 s autoexposure, even when the camera is in a light-tight box and
$ raspistill -o /tmp/foo.png --exposure 2
RaspiStill: Unknown exposure mode: 2
so the command line doesn't support an exposure time, and doesn't do anything sensible with exposure mode.

**Comment by tejonbiker** [comment]
Hi, I noticed the whole time that takes the -ss to 6000000 (Max value), but I don't know where the camera start to record, as far I can see, the camera waits 6 seconds for capture something, later take another capture of 6 seconds (this image is showed in the preview image in a HDMI monitor), later wait another 6 seconds and start to record the ultimate image (another 6 seconds),  There's any way to know where the camera start to record the ultimate image?

**Comment by JamesH65** [comment]
There are some threads on the forum which cover exactly this topic of using
long exposure times.

**Comment by Ruffio** [comment]
@dmopalmer @jollyjollyjolly is this still an issue?

**Comment by bbozon** [comment]
I'm still having the issue that the camera takes ~40 seconds for a 6 seconde exposure. Does anybody know how to fix this?

James, do you know the status?

Thanks in advance!!!

**Comment by JamesH65** [comment]
@6by9 Cannot remember what we suggest as a solution for this.

**Comment by 6by9** [comment]
It's almost certainly just mode switching, so pretty much inherent. 40 seconds sounds high though - I thought it was around 24.

Two constraints:
- whenever the sensor starts streaming it produces one corrupted frame.
- whenever the GPU has requested a frame, it completes it.

In starting raspistill, regardless of the -t setting, it starts preview and requests a frame. Both the corrupt frame and preview frame will require the exposure time of 6 seconds. T=12secs now.

Assuming the capture has been requested by 12secs, then the sensor gets stopped, reprogrammed for the capture mode, and restarted. Starting the sensor means dropping a frame, so another 12 secs.

If burst mode hasn't been requested then as soon as the capture is completed it will mode switch back to preview and request a preview frame. I thought that shutting down would abort that frame, but I suspect that it may still complete it and taking another 12seconds.

There are a couple of things that could be checked to improve this, but it's not a priority at the moment.

**Comment by bbozon** [comment]
It works!!! Thank you very much. I forgot to put -bm and -ex off

Sorry for the trouble...
