### ISSUE TITLE
buffer handling PNG encoding is causing an error

### ISSUE THREAD

**Issue by alexamy1987** [raspberrypi/userland#78]
buffer handling PNG encoding is causing an error which produces a bright band at the top of the image. 
EDIT: This occurs not only on green light as first expected.
![550nm](https://f.cloud.github.com/assets/5347707/1058566/f2f61530-118a-11e3-8b0b-97ecc480cb3b.png)

**Comment by Ruffio** [comment]
@JamesH65 any progress on this issue?

**Comment by 6by9** [comment]
Wow, an oldie.

This will actually be a firmware issue but exposed by raspistill.
At a guess, when the YUV to RGB conversion required for PNG is done it is probably picking up a different colourspace for the first vs subsequent stripes. I'll try to have a look - James no longer has firmware access.

**Comment by popcornmix** [comment]
Latest rpi-update has a potential fix for this issue

**Comment by popcornmix** [comment]
I believe this is resolved. Please reopen if it is not.
